import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MontiNavBar from "@/components/montiNav/montiNavBar";
import NavSearchBar from "@/components/montiNav/navSearchBar";
import NavUserArea from "@/components/montiNav/navUserArea";
import Image from "next/image";
import Link from "next/link";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex justify-around mx-2 mb-4 p-3 bg-zinc-50 dark:bg-black">
          <Link href="/">
            <Image
              className="dark:invert"
              src="/monti_logo_notext.png"
              alt="monti logo"
              width={100}
              height={20}
              priority
            />
          </Link>
          <MontiNavBar />
          <NavSearchBar />
          <NavUserArea />

        </div>
        {children}
      </body>
    </html>
  );
}
